server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth
    username: 'postgres'
    password: 'lost4815162342'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true

logging:
  level:
    org:
      springframework:
        web: TRACE