package advice;

public enum ExceptionStatus {

    ORDER_NOT_FOUND,
    RESTAURANT_NOT_FOUND,
    CUSTOMER_NOT_FOUND,
    COURIER_NOT_FOUND,
    ORDER_ITEM_NOT_FOUND,
    RESTAURANT_MENU_ITEM_NOT_FOUND
}
