server:
  port: 8081
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: kitchen-service

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:9000

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
      org:
        hibernate:
          envers:
            revision_field_name: rev_id
            revision_type_field_name: rev_type
    show-sql: 'true'

  datasource:
    password: 'lost4815162342'
    url: jdbc:postgresql://localhost:5432/postgres
    username: 'postgres'

feign:
  services:
    delivery-service:
      url: http://localhost:8080