server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: kitchen-service

notification:
  service: http://localhost:8083
  kitchenLogin: admin
  kitchenPass: admin
